Repository nonmilk/coffee, pull requests merged in 2025-01, with the labels that each got.

#3 feat: initial structure
  app/build.gradle.kts
  app/src/main/java/io/github/nonmilk/coffee/App.java
  app/src/main/java/io/github/nonmilk/coffee/Camerer.java
  app/src/main/java/io/github/nonmilk/coffee/Grinder.java
  app/src/main/java/io/github/nonmilk/coffee/Named.java
  app/src/main/java/io/github/nonmilk/coffee/NamedCamera.java
  app/src/main/java/io/github/nonmilk/coffee/NamedScene.java
  app/src/main/java/io/github/nonmilk/coffee/Scener.java
  app/src/main/java/io/github/nonmilk/coffee/Viewer.java
  app/src/main/resources/io/github/nonmilk/coffee/app.fxml
  app/src/main/resources/io/github/nonmilk/coffee/cameras.fxml
  app/src/main/resources/io/github/nonmilk/coffee/scenes.fxml
  app/src/main/resources/io/github/nonmilk/coffee/styles.css
  app/src/main/resources/io/github/nonmilk/coffee/view.fxml
Labels: type/fix, type/feat, type/refactor, type/build

#5 feat: Modeler
  app/src/main/java/io/github/nonmilk/coffee/App.java
  app/src/main/java/io/github/nonmilk/coffee/Grinder.java
  app/src/main/java/io/github/nonmilk/coffee/Modeler.java
  app/src/main/java/io/github/nonmilk/coffee/NamedModel.java
  app/src/main/java/io/github/nonmilk/coffee/Scener.java
  app/src/main/java/io/github/nonmilk/coffee/Viewer.java
  app/src/main/resources/io/github/nonmilk/coffee/app.fxml
  app/src/main/resources/io/github/nonmilk/coffee/models.fxml
  app/src/main/resources/io/github/nonmilk/coffee/styles.css
Labels: type/fix, type/feat

#7 fix(Modeler): handle null selections
  app/src/main/java/io/github/nonmilk/coffee/Modeler.java
Labels: type/fix

#8 feat: initial Viewer setup
  app/src/main/java/io/github/nonmilk/coffee/Viewer.java
  app/src/main/resources/io/github/nonmilk/coffee/app.fxml
  app/src/main/resources/io/github/nonmilk/coffee/styles.css
  app/src/main/resources/io/github/nonmilk/coffee/view.fxml
Labels: type/fix, type/feat

#9 feat: catppuccin styling
  app/src/main/resources/io/github/nonmilk/coffee/app.fxml
  app/src/main/resources/io/github/nonmilk/coffee/styles.css
  app/src/main/resources/io/github/nonmilk/coffee/view.fxml
Labels: type/fix, type/feat

#10 feat: menu scroll
  app/src/main/resources/io/github/nonmilk/coffee/app.fxml
  app/src/main/resources/io/github/nonmilk/coffee/styles.css
Labels: type/fix, type/feat

#11 feat: initial texture setup
  app/src/main/java/io/github/nonmilk/coffee/Modeler.java
  app/src/main/resources/io/github/nonmilk/coffee/models.fxml
Labels: type/fix, type/feat, type/refactor

#14 feat(Modeler): new layout
  app/src/main/java/io/github/nonmilk/coffee/NamedModel.java
  app/src/main/resources/io/github/nonmilk/coffee/app.fxml
  app/src/main/resources/io/github/nonmilk/coffee/models.fxml
  app/src/main/resources/io/github/nonmilk/coffee/styles.css
Labels: type/fix, type/feat

#16 feat: cameras layout
  app/src/main/java/io/github/nonmilk/coffee/Camerer.java
  app/src/main/java/io/github/nonmilk/coffee/NamedCamera.java
  app/src/main/resources/io/github/nonmilk/coffee/cameras.fxml
  app/src/main/resources/io/github/nonmilk/coffee/styles.css
Labels: type/feat

#17 feat: new scenes layout
  app/src/main/java/io/github/nonmilk/coffee/NamedScene.java
  app/src/main/resources/io/github/nonmilk/coffee/scenes.fxml
Labels: type/feat

#21 build: add clean scripts
  clean.bat
  clean.sh
Labels: type/build

#13 feat(camera controls): add functionality via mouse events
  app/src/main/java/io/github/nonmilk/coffee/CameraController.java
  app/src/main/java/io/github/nonmilk/coffee/Camerer.java
  app/src/main/java/io/github/nonmilk/coffee/Grinder.java
  app/src/main/java/io/github/nonmilk/coffee/Viewer.java
Labels: type/feat, type/chore, type/refactor

#22 feat(camera-controller): add initial angles for new camera
  app/src/main/java/io/github/nonmilk/coffee/CameraController.java
Labels: type/feat

#24 refactor(camera controls): optimize methods
  app/src/main/java/io/github/nonmilk/coffee/CameraController.java
Labels: type/refactor

#25 feat: Modeler logic
  app/src/main/java/io/github/nonmilk/coffee/Modeler.java
  app/src/main/java/io/github/nonmilk/coffee/NamedModel.java
Labels: type/fix, type/feat, type/style

#26 fix: add default window size
  app/src/main/java/io/github/nonmilk/coffee/App.java
Labels: type/fix

#27 feat(camera controls): simple movement
  app/src/main/java/io/github/nonmilk/coffee/CameraController.java
Labels: type/feat, type/refactor

#28 fix(Modeler): default values on fields
  app/src/main/java/io/github/nonmilk/coffee/Modeler.java
Labels: type/fix

#29 feat: camera logic
  app/src/main/java/io/github/nonmilk/coffee/CameraController.java
  app/src/main/java/io/github/nonmilk/coffee/Camerer.java
  app/src/main/java/io/github/nonmilk/coffee/Grinder.java
  app/src/main/java/io/github/nonmilk/coffee/Viewer.java
  app/src/main/resources/io/github/nonmilk/coffee/cameras.fxml
Labels: type/fix, type/feat, type/refactor, type/style

#31 fix(camera-controller): adapt mouse motions
  app/src/main/java/io/github/nonmilk/coffee/CameraController.java
Labels: type/fix

#30 feat(camera controls): sensitivity
  app/src/main/java/io/github/nonmilk/coffee/CameraController.java
Labels: type/fix, type/feat, type/chore, type/refactor

#32 fix(camera-controller): replace sense multipliers
  app/src/main/java/io/github/nonmilk/coffee/CameraController.java
Labels: type/fix

#33 feat: error handling
  app/src/main/java/io/github/nonmilk/coffee/App.java
  app/src/main/java/io/github/nonmilk/coffee/Camerer.java
  app/src/main/java/io/github/nonmilk/coffee/CoffeeError.java
  app/src/main/java/io/github/nonmilk/coffee/Modeler.java
  app/src/main/java/io/github/nonmilk/coffee/Scener.java
Labels: type/fix, type/feat, type/style

#34 feat: vertex selection
  app/src/main/java/io/github/nonmilk/coffee/CameraController.java
  app/src/main/java/io/github/nonmilk/coffee/Selection.java
  app/src/main/java/io/github/nonmilk/coffee/Viewer.java
Labels: type/fix, type/feat, type/refactor, type/style

#36 fix: infinite errors
  app/src/main/java/io/github/nonmilk/coffee/App.java
  app/src/main/java/io/github/nonmilk/coffee/Grinder.java
  app/src/main/java/io/github/nonmilk/coffee/Viewer.java
Labels: type/fix, type/feat

#37 feat: settings
  app/src/main/java/io/github/nonmilk/coffee/Grinder.java
  app/src/main/resources/io/github/nonmilk/coffee/app.fxml
  app/src/main/resources/io/github/nonmilk/coffee/cameras.fxml
  app/src/main/resources/io/github/nonmilk/coffee/models.fxml
  app/src/main/resources/io/github/nonmilk/coffee/scenes.fxml
  app/src/main/resources/io/github/nonmilk/coffee/styles.css
Labels: type/fix, type/feat, type/refactor

#39 fix(Grinder): get field text twice
  app/src/main/java/io/github/nonmilk/coffee/Grinder.java
Labels: type/fix

#40 feat(camera controls): keyboard support
  app/src/main/java/io/github/nonmilk/coffee/CameraController.java
  app/src/main/java/io/github/nonmilk/coffee/Viewer.java
Labels: type/fix, type/feat, type/chore

#41 feat: select and activate on new items
  app/src/main/java/io/github/nonmilk/coffee/Camerer.java
  app/src/main/java/io/github/nonmilk/coffee/Modeler.java
  app/src/main/java/io/github/nonmilk/coffee/Scener.java
Labels: type/feat

#42 feat: assets
  app/src/main/java/io/github/nonmilk/coffee/Modeler.java
  assets/.gitignore
  assets/README.md
Labels: type/fix, type/feat

#44 refactor(camera-controls): rm unnecessary f and finalize vars
  app/src/main/java/io/github/nonmilk/coffee/CameraController.java
Labels: type/chore, type/refactor

#43 feat(model transforms): keyboard controls
  app/src/main/java/io/github/nonmilk/coffee/Grinder.java
  app/src/main/java/io/github/nonmilk/coffee/Modeler.java
  app/src/main/java/io/github/nonmilk/coffee/Viewer.java
Labels: type/fix, type/feat, type/refactor

#46 build: deploy binary
  app/build.gradle.kts
  app/java.ico
Labels: type/build

#47 feat: vertex deletion
  app/src/main/java/io/github/nonmilk/coffee/Modeler.java
  app/src/main/java/io/github/nonmilk/coffee/Viewer.java
Labels: type/fix, type/feat

#48 build: windows scripts
  build.bat
  clean.bat
  cold-start.bat
Labels: type/fix, type/build

#49 feat: vertex deletion button
  app/src/main/java/io/github/nonmilk/coffee/Grinder.java
  app/src/main/java/io/github/nonmilk/coffee/Viewer.java
  app/src/main/resources/io/github/nonmilk/coffee/app.fxml
Labels: type/fix, type/feat

#50 feat: live model update
  app/src/main/java/io/github/nonmilk/coffee/Modeler.java
Labels: type/fix, type/feat, type/style

#51 feat(camera-controls): add field tracking on key events
  app/src/main/java/io/github/nonmilk/coffee/CameraController.java
Labels: type/feat

#52 fix: disable orthographic cameras btn
  app/src/main/resources/io/github/nonmilk/coffee/cameras.fxml
Labels: type/fix

#54 fix(Modeler): change initial directory path
  app/src/main/java/io/github/nonmilk/coffee/Modeler.java
Labels: type/fix
